### PR TITLE
Details page

### PR DESCRIPTION
**Pull request by roshan-bajgain**
### This branch includes the following feature
- When the user selects a specific item, they can see the [details page](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005579) with its full description (skip the "Rotate image" button).
- In the details page, the user can click the "Reserve" button
- Make the app responsive, creating both mobile and desktop versions.
### Image for reference
desktop
### Mobile
mobile

### CODE REVIEW

**Review by vikipretium — APPROVED** [review]
### **STATUS: APPROVED  ✔️** 
------
Hi @roshan-bajgain ,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟


https://user-images.githubusercontent.com/20333314/181043037-0e438492-0b1c-433c-93cc-1f85e0b93f3b.mp4



## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:

> ## [Optional] suggestions:
> * [ ]  Please check my inline comments.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏.

> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @vikipretium in your question so I can receive the notification

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by daudi13 — CHANGES_REQUESTED** [review]
@roshan-bajgain good job implementing the features of the project. However, I just have a few remarks to make
- Please remove the padding surrounding your component.
- align the items on your component to the centre there is a lot of space below check the design. In your mobile version, the elements are aligned right instead of centre
- The navbar on your component should not be inside of your working div but outside.(check the suggestion below)

**Comment by daudi13** [comment]
image
try and add your navbar like this instead of putting it inside a div to solve the issue of a floating navbar

**Comment by daudi13** [comment]
image
This is what the mobile display looks like, Please align everything to the centre and maybe increase the width of the details card in relation to the screen size with some padding.

**Comment by roshan-bajgain** [comment]
@daudi13, you can check now.

**Pull request merged**
